FROM misskey/misskey:latest

ARG MISSKEY_DB_HOST
ARG MISSKEY_DB_PORT
ARG MISSKEY_DB_PASS
ARG MISSKEY_DB_USER
ARG MISSKEY_DB_DB
ARG MISSKEY_REDIS_HOST
ARG MISSKEY_REDIS_PORT
ARG MISSKEY_REDIS_PASS
ARG MISSKEY_ID
ARG MISSKEY_URL
ARG MISSKEY_PORT

COPY env.js ./
RUN mkdir .config && node env.js > .config/default.yaml
